## 1. Elementwise Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [1]:
import numpy as np

In [2]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7]])

In [3]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[1, 2, 3],
        [9, 8, 7]]))

### Arithmetic Operations


In [4]:
# a+b
np.add(a,b)

array([[ 5,  7,  9],
       [14, 15, 16]])

In [5]:
# a-b
np.subtract(a,b)

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [6]:
# a *b
np.multiply(a,b)

array([[ 4, 10, 18],
       [45, 56, 63]])

In [7]:
# a ** 2
#np.square(b)
np.power(a,b)

array([[      4,      25,     216],
       [1953125, 5764801, 4782969]])

In [8]:
#a%b
quo, rem = np.divmod(a,2)

In [9]:
rem

array([[0, 1, 0],
       [1, 1, 1]])

In [10]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [11]:
np.ceil(np.sqrt(a))

array([[2., 3., 3.],
       [3., 3., 3.]])

### Trignometric

In [12]:
new = 1 / np.sin(a)
print(new)

[[-1.32134871 -1.04283521 -3.57889955]
 [-1.04283521  1.52210106  2.42648664]]


In [13]:
1 / np.tan(b)

array([[ 0.64209262, -0.45765755, -7.01525255],
       [-2.21084541, -0.14706506,  1.14751542]])

### Rounding operations

In [14]:
np.round(new, decimals = 3)

array([[-1.321, -1.043, -3.579],
       [-1.043,  1.522,  2.426]])

In [15]:
np.around(new, decimals=4)

array([[-1.3213, -1.0428, -3.5789],
       [-1.0428,  1.5221,  2.4265]])

In [16]:
np.fix(new)

array([[-1., -1., -3.],
       [-1.,  1.,  2.]])

In [17]:
np.floor(new)

array([[-2., -2., -4.],
       [-2.,  1.,  2.]])

## 2. Matrix Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [21]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7], [9,4,7]])

b



array([[1, 2, 3],
       [9, 8, 7],
       [9, 4, 7]])

In [22]:
np.dot(a,b)

array([[103,  72,  89],
       [149, 102, 127]])

In [23]:
# b.T
np.transpose(b)

array([[1, 9, 9],
       [2, 8, 4],
       [3, 7, 7]])

In [25]:
np.trace(b) #>- add diagonal (eg : 1+8+7)

np.int64(16)

In [26]:
np.linalg.det(b)

np.float64(-79.99999999999997)

In [27]:
# B.B-1 = I
np.dot(b, np.linalg.inv(b)
      ).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [30]:
# Solve Equations: x + 2*y = 1 and 3*x + 5*y = 2
a = np.array([[1,2],
             [3,5]])

b = np.array([1,2])             


In [32]:
np.linalg.solve(a,b)

array([-1.,  1.])