## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(10,50, size = (5,2,3))

In [4]:
c = np.random.randint(0,10, (4,2,2))
arr

array([[[22, 35, 37],
        [25, 46, 40]],

       [[23, 37, 33],
        [10, 45, 27]],

       [[36, 37, 20],
        [22, 42, 11]],

       [[33, 28, 10],
        [45, 36, 24]],

       [[39, 16, 27],
        [31, 16, 26]]], dtype=int32)

In [5]:
arr.ndim

3

In [6]:
arr.shape

(5, 2, 3)

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr_T=arr.T
arr_T

array([[[22, 23, 36, 33, 39],
        [25, 10, 22, 45, 31]],

       [[35, 37, 37, 28, 16],
        [46, 45, 42, 36, 16]],

       [[37, 33, 20, 10, 27],
        [40, 27, 11, 24, 26]]], dtype=int32)

In [9]:
arr_T.shape

(3, 2, 5)

In [10]:
arr.shape

(5, 2, 3)

In [11]:
arr.reshape(10,3)

array([[22, 35, 37],
       [25, 46, 40],
       [23, 37, 33],
       [10, 45, 27],
       [36, 37, 20],
       [22, 42, 11],
       [33, 28, 10],
       [45, 36, 24],
       [39, 16, 27],
       [31, 16, 26]], dtype=int32)

In [12]:
arr.reshape(15,2)

array([[22, 35],
       [37, 25],
       [46, 40],
       [23, 37],
       [33, 10],
       [45, 27],
       [36, 37],
       [20, 22],
       [42, 11],
       [33, 28],
       [10, 45],
       [36, 24],
       [39, 16],
       [27, 31],
       [16, 26]], dtype=int32)

In [13]:
arr.flatten()

array([22, 35, 37, 25, 46, 40, 23, 37, 33, 10, 45, 27, 36, 37, 20, 22, 42,
       11, 33, 28, 10, 45, 36, 24, 39, 16, 27, 31, 16, 26], dtype=int32)

### 0 > column wise
### 1 > row wise

In [15]:
#arr.sum()
arr.sum()
arr.sum(axis =1)

array([[47, 81, 77],
       [33, 82, 60],
       [58, 79, 31],
       [78, 64, 34],
       [70, 32, 53]])

In [16]:
np.sum(
    [
        [0,1],
        [0,5]

    ],
 axis = 0)   

array([0, 6])

In [17]:
np.sum(
    [
        [0,1],
        [0,5]

    ],
 axis = 1)  

array([1, 5])

In [18]:
arr.prod(dtype = float)

np.float64(9.45084284472511e+42)

In [20]:
arr

array([[[22, 35, 37],
        [25, 46, 40]],

       [[23, 37, 33],
        [10, 45, 27]],

       [[36, 37, 20],
        [22, 42, 11]],

       [[33, 28, 10],
        [45, 36, 24]],

       [[39, 16, 27],
        [31, 16, 26]]], dtype=int32)

In [19]:
arr.prod(axis =0)

array([[23443992, 21465920,  6593400],
       [ 7672500, 50077440,  7413120]])

In [21]:
arr.cumsum()

array([ 22,  57,  94, 119, 165, 205, 228, 265, 298, 308, 353, 380, 416,
       453, 473, 495, 537, 548, 581, 609, 619, 664, 700, 724, 763, 779,
       806, 837, 853, 879])

In [22]:
arr.max()

np.int32(46)

In [23]:
arr.argmax()
#arr.argmax(axis = 0)

np.int64(4)

In [25]:
arr.clip(10,20)

array([[[20, 20, 20],
        [20, 20, 20]],

       [[20, 20, 20],
        [10, 20, 20]],

       [[20, 20, 20],
        [20, 20, 11]],

       [[20, 20, 10],
        [20, 20, 20]],

       [[20, 16, 20],
        [20, 16, 20]]], dtype=int32)

In [26]:
arr1 = np.random.randint(low = -10, high = 10, size = (2,3))
arr2 = np.random.randint(low = 0, high = 11, size = (2,3))

In [27]:
arr1, arr2

(array([[-1, -7,  6],
        [ 2,  4,  0]], dtype=int32),
 array([[7, 2, 7],
        [4, 2, 4]], dtype=int32))

In [29]:
np.vstack([arr1, arr2]) #< same columns

array([[-1, -7,  6],
       [ 2,  4,  0],
       [ 7,  2,  7],
       [ 4,  2,  4]], dtype=int32)

In [30]:
np.hstack((arr1, arr2)) #< same rows

array([[-1, -7,  6,  7,  2,  7],
       [ 2,  4,  0,  4,  2,  4]], dtype=int32)