## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [5]:
import numpy as np

3

In [8]:
c = np.random.randint(0,10, (4,2,2))
arr

array([[[13, 33, 26],
        [32, 21, 11]],

       [[46, 30, 10],
        [17, 40, 20]],

       [[35, 15, 11],
        [28, 13, 47]],

       [[13, 48, 27],
        [36, 48, 22]],

       [[22, 33, 23],
        [41, 14, 15]]], dtype=int32)

In [9]:
arr.ndim

3

In [10]:
arr.shape

(5, 2, 3)

In [11]:
arr.dtype

dtype('int32')

In [14]:
arr_T=arr.T
arr_T

array([[[13, 46, 35, 13, 22],
        [32, 17, 28, 36, 41]],

       [[33, 30, 15, 48, 33],
        [21, 40, 13, 48, 14]],

       [[26, 10, 11, 27, 23],
        [11, 20, 47, 22, 15]]], dtype=int32)

In [15]:
arr_T.shape

(3, 2, 5)

In [16]:
arr.shape

(5, 2, 3)

In [17]:
arr.reshape(10,3)

array([[13, 33, 26],
       [32, 21, 11],
       [46, 30, 10],
       [17, 40, 20],
       [35, 15, 11],
       [28, 13, 47],
       [13, 48, 27],
       [36, 48, 22],
       [22, 33, 23],
       [41, 14, 15]], dtype=int32)

In [19]:
arr.reshape(15,2)

array([[13, 33],
       [26, 32],
       [21, 11],
       [46, 30],
       [10, 17],
       [40, 20],
       [35, 15],
       [11, 28],
       [13, 47],
       [13, 48],
       [27, 36],
       [48, 22],
       [22, 33],
       [23, 41],
       [14, 15]], dtype=int32)