NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [3]:
import numpy as np


In [4]:
np.zeros(shape = (5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.full((2,2), 4.5)

array([[4.5, 4.5],
       [4.5, 4.5]])

In [11]:
np.full((3,4), 3.4)

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4]])

In [12]:
np.random.rand(2,3)

array([[0.96534884, 0.2151039 , 0.54088798],
       [0.16445818, 0.26591347, 0.12635585]])

In [13]:
np.random.randint(low = 4, high = 30, size= (2,2))

array([[26, 14],
       [25, 18]], dtype=int32)

In [15]:
np.linspace(start = 0, stop = 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(start = (0,1,2), stop =(10,20,30), num=5, axis=0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [4]:
np.linspace(start = (0,1,2), stop =(10,20,30), num=5, axis=1)

array([[ 0.  ,  2.5 ,  5.  ,  7.5 , 10.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 2.  ,  9.  , 16.  , 23.  , 30.  ]])

## Accessing an Array

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]


 ### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [5]:
#1D
a = np.array([1,2,3,4,5])

In [6]:
a[0]

np.int64(1)

In [7]:
a[-1]

np.int64(5)

In [22]:
a[2:10:2]

array([3, 5])

In [23]:
#2D
b = np.random.randint(0,10,(5,5))

In [24]:
b

array([[6, 8, 2, 5, 4],
       [1, 5, 4, 3, 8],
       [4, 4, 2, 4, 1],
       [8, 7, 6, 1, 1],
       [0, 4, 8, 1, 0]], dtype=int32)

In [25]:
b[::2]

array([[6, 8, 2, 5, 4],
       [4, 4, 2, 4, 1],
       [0, 4, 8, 1, 0]], dtype=int32)

In [26]:
b[::2][1]

array([4, 4, 2, 4, 1], dtype=int32)

In [28]:
#slicing 2D array : array [ <row_slice, column_slice>]
b[::2, 1:4]

array([[8, 2, 5],
       [4, 2, 4],
       [4, 8, 1]], dtype=int32)

In [10]:
b[0]

array([9, 3], dtype=int32)

In [11]:
b[0][0]

np.int32(9)

In [12]:
b[1][1]

np.int32(5)

In [13]:
#3D
c = np.random.randint(0,10, (4,2,2))

In [14]:
c

array([[[9, 9],
        [1, 1]],

       [[0, 0],
        [3, 5]],

       [[6, 7],
        [3, 5]],

       [[5, 4],
        [4, 6]]], dtype=int32)

In [15]:
c[-1]

array([[5, 4],
       [4, 6]], dtype=int32)

In [16]:
c[-1][0]

array([5, 4], dtype=int32)

In [17]:
c[-1][0][0]

np.int32(5)

In [18]:
c[0]


array([[9, 9],
       [1, 1]], dtype=int32)

In [19]:
c[1][1][1]

np.int32(5)

In [29]:
c[::, ::, ::]

array([[[9, 9],
        [1, 1]],

       [[0, 0],
        [3, 5]],

       [[6, 7],
        [3, 5]],

       [[5, 4],
        [4, 6]]], dtype=int32)

In [30]:
c[::2, ::2, ::2]

array([[[9]],

       [[6]]], dtype=int32)

In [31]:
c = np.random.randint(0,10, (4,3,3))

In [32]:
c

array([[[4, 1, 4],
        [8, 6, 2],
        [6, 9, 7]],

       [[5, 2, 6],
        [2, 4, 4],
        [8, 9, 2]],

       [[6, 4, 3],
        [1, 8, 3],
        [0, 4, 8]],

       [[7, 4, 4],
        [4, 2, 5],
        [2, 9, 9]]], dtype=int32)

In [33]:
c[1:3, 0:2, 0:3]


array([[[5, 2, 6],
        [2, 4, 4]],

       [[6, 4, 3],
        [1, 8, 3]]], dtype=int32)

In [35]:
c[0:3, 1:3, 1:3] 

array([[[6, 2],
        [9, 7]],

       [[4, 4],
        [9, 2]],

       [[8, 3],
        [4, 8]]], dtype=int32)

In [36]:
c = np.random.randint(0,10, (16,3,500,500))

In [37]:
c

array([[[[9, 4, 9, ..., 8, 7, 3],
         [8, 5, 5, ..., 2, 3, 3],
         [6, 0, 0, ..., 9, 7, 9],
         ...,
         [8, 6, 3, ..., 7, 5, 6],
         [1, 8, 0, ..., 9, 2, 9],
         [5, 4, 9, ..., 4, 6, 4]],

        [[9, 7, 7, ..., 7, 0, 1],
         [1, 3, 3, ..., 2, 1, 4],
         [6, 1, 9, ..., 9, 2, 4],
         ...,
         [5, 6, 8, ..., 5, 8, 3],
         [4, 8, 8, ..., 9, 3, 8],
         [9, 4, 9, ..., 6, 2, 8]],

        [[0, 8, 4, ..., 7, 9, 9],
         [6, 7, 2, ..., 9, 2, 7],
         [9, 2, 8, ..., 7, 2, 6],
         ...,
         [1, 2, 5, ..., 4, 8, 7],
         [6, 5, 3, ..., 8, 6, 0],
         [8, 2, 1, ..., 9, 6, 7]]],


       [[[8, 4, 2, ..., 9, 5, 8],
         [5, 6, 4, ..., 5, 4, 1],
         [0, 2, 2, ..., 0, 9, 3],
         ...,
         [3, 0, 3, ..., 0, 8, 8],
         [4, 5, 5, ..., 4, 8, 0],
         [7, 6, 9, ..., 1, 2, 4]],

        [[9, 3, 8, ..., 3, 0, 5],
         [5, 6, 2, ..., 8, 3, 1],
         [5, 0, 7, ..., 9, 5, 0],
         ...,
  

In [40]:
c = np.random.randint(0,10,(4,3,5,5))

In [39]:
c

array([[[[3, 6, 9, 9, 0],
         [4, 3, 5, 8, 7],
         [0, 3, 6, 6, 1],
         [0, 4, 6, 9, 2],
         [6, 0, 1, 9, 7]],

        [[2, 5, 3, 4, 0],
         [6, 8, 8, 3, 8],
         [7, 3, 2, 5, 7],
         [9, 3, 4, 8, 0],
         [0, 7, 1, 1, 6]],

        [[9, 2, 3, 8, 2],
         [3, 4, 2, 8, 7],
         [4, 2, 9, 9, 0],
         [2, 6, 8, 8, 8],
         [3, 0, 8, 3, 8]]],


       [[[8, 6, 6, 7, 7],
         [8, 1, 7, 3, 6],
         [8, 2, 6, 8, 1],
         [1, 6, 4, 4, 9],
         [4, 0, 8, 0, 5]],

        [[5, 5, 6, 6, 1],
         [4, 5, 1, 5, 3],
         [6, 5, 2, 4, 4],
         [2, 4, 7, 6, 0],
         [3, 0, 4, 1, 1]],

        [[4, 8, 7, 5, 9],
         [2, 9, 8, 5, 6],
         [7, 3, 3, 1, 3],
         [1, 3, 8, 8, 0],
         [0, 3, 0, 2, 4]]],


       [[[2, 7, 6, 7, 8],
         [4, 8, 2, 1, 1],
         [8, 6, 2, 4, 0],
         [7, 8, 6, 6, 0],
         [6, 4, 7, 7, 0]],

        [[5, 7, 5, 4, 2],
         [5, 2, 8, 5, 8],
         [1, 8, 1, 7

## Boolean or Masking Indexing

In [69]:
a = np.random.randint(1,7,(5,5))
a

array([[3, 2, 1, 4, 2],
       [1, 4, 3, 2, 1],
       [5, 6, 4, 1, 2],
       [4, 1, 1, 4, 4],
       [2, 3, 6, 2, 6]], dtype=int32)

In [70]:
mask = a >= 4

In [71]:
a[mask]

array([4, 4, 5, 6, 4, 4, 4, 4, 6, 6], dtype=int32)

In [72]:
a

array([[3, 2, 1, 4, 2],
       [1, 4, 3, 2, 1],
       [5, 6, 4, 1, 2],
       [4, 1, 1, 4, 4],
       [2, 3, 6, 2, 6]], dtype=int32)

In [73]:
mask = [True,False,True,True, False]

In [76]:
a[mask]

array([[3, 2, 1, 4, 2],
       [5, 6, 4, 1, 2],
       [4, 1, 1, 4, 4]], dtype=int32)

In [77]:
a[mask, mask]

array([3, 4, 4], dtype=int32)