In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt

In [2]:
data_df = pd.read_csv("https://www.statlearning.com/s/Advertising.csv", index_col=0)

In [3]:
data_df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [4]:
x = data_df['TV'].to_numpy()
y = data_df['sales'].to_numpy()


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 989) 

In [7]:
X_train

array([191.1,  11.7,  50. ,  25.6,  88.3, 187.8,  17.2, 255.4,   0.7,
       125.7, 104.6, 222.4, 107.4, 172.5, 116. , 135.2, 188.4,  44.7,
       131.7, 213.4,   5.4, 175.1,  59.6, 250.9, 139.5,  76.4, 220.5,
       283.6,  68.4,  43.1, 214.7,  27.5, 280.7,  26.8, 187.9, 292.9,
       193.2, 182.6, 238.2, 230.1,  53.5, 134.3, 266.9,  62.3,  39.5,
       102.7,  48.3, 276.7, 164.5,  94.2, 290.7, 149.8, 222.4, 216.4,
       225.8, 261.3, 248.8,  57.5, 204.1, 253.8,  73.4,  96.2,  97.2,
       112.9, 296.4,  13.1, 206.9, 210.8, 151.5, 199.1,  13.2, 229.5,
       199.8,  90.4, 228. ,  31.5, 220.3, 177. ,  74.7, 195.4, 240.1,
        17.9, 109.8,   7.8,  23.8, 239.8, 170.2,  93.9, 243.2,   8.4,
       131.1,  69. , 209.6, 280.2,  16.9,  76.4,  75.5, 227.2, 184.9,
        70.6, 276.9, 171.3, 217.7, 215.4, 273.7,  19.6, 110.7,  56.2,
       228.3, 139.3, 184.9,  28.6, 142.9, 202.5, 240.1, 224. , 120.5,
       265.6, 193.7, 234.5,  25.1, 197.6, 123.1, 121. , 218.5, 289.7,
       293.6, 168.4,

In [8]:
lin_reg = LinearRegression()
lin_reg.fit(X_train.reshape(-1,1), y_train)

LinearRegression()

In [9]:
print(f"y  = {lin_reg.intercept_} + {lin_reg.coef_[0]} x")


y  = 6.858509764823011 + 0.04842623831035565 x


In [10]:
y_pred= lin_reg.predict(X_test.reshape(-1,1))
y_pred

array([18.09823968,  8.69870682,  7.27981804, 13.652711  ,  8.94083801,
       17.06191818,  8.70839207,  8.64543796,  7.79797879, 18.47596434,
       17.50259695, 14.93600631, 10.14180872, 14.87789483, 19.58976782,
       12.67934361, 20.7858959 , 13.53648803, 10.20960546, 10.09822511,
       20.48565323, 14.10791764, 14.77619973, 13.59944214, 10.49532026,
       11.49290077, 13.99169467, 15.42995395,  8.06916572, 11.72050409,
       10.50500551,  9.01347737,  7.76892305, 16.78588862, 13.45416342,
       11.08127775, 19.70114816, 12.17571073, 18.44690859, 20.62608932])

# Performance Matrix

In [11]:
from sklearn.metrics import max_error, mean_squared_error, mean_absolute_error, r2_score

In [12]:
max_error(y_test, y_pred)

np.float64(7.58976781661551)

In [13]:
mean_squared_error(y_test, y_pred)

10.209617603110354

In [14]:
mean_absolute_error(y_test, y_pred)

2.4910506561061587

# R2 cofficient

### R2 Cofficient

R-squared is a goodness-of-fit measure for linear regression models. This statistic indicates the percentage of the variance in the dependent variable that the independent variables explain collectively. R-squared measures the strength of the relationship between your model and the dependent variable on a convenient 0 – 100% scale.

R-squared represents the proportion of the variance in the dependent variable that is predictable from the independent variables. It ranges from 0 to 1, where 1 indicates a perfect fit. It is calculated as:

$R^2 = 1 - \frac{RSS}{TSS}$

Where RSS is the residual sum of squares and TSS is the total sum of squares.

The RSS (Residual Sum of Squares) represents the sum of squared differences between the observed dependent variable values (y) and the predicted values (ŷ) obtained from the linear regression model. Mathematically, it is calculated as follows:

$RSS = Σ(y - ŷ)^2$

On the other hand, the TSS (Total Sum of Squares) represents the total variation in the dependent variable (y) from its mean (ȳ). It measures the sum of squared differences between each observed dependent variable value (y) and the mean of the dependent variable (ȳ). Mathematically, it is calculated as follows:

$TSS = Σ(y - ȳ)^2$

R-squared is always between 0 and 100%:

* 0% represents a model that does not explain any of the variation in the response variable around its mean. The mean of the dependent variable predicts the dependent variable as well as the regression model.
* 100% represents a model that explains all the variation in the response variable around its mean.

In [15]:
r2_score(y_test, y_pred)

0.5697181446883102

In [16]:

x = data_df['newspaper'].to_numpy()
y = data_df['sales'].to_numpy()


In [17]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 989)

In [18]:
X_train

array([ 18.2,  45.2,  18.4,   9.3,  73.4,   9.5,  69.3,   5.5,   8.7,
        79.2,  34.4,  49.8,  10.9,  30.7,  23.1,  45.9,  25.6,  20.6,
        34.6,  13.1,   9.4,  31.5,  43.1,  72.3,  26.6,  22.3,  37.9,
        66.2,  35.6,  35.1,   4. ,  20.7,  37. ,  19.3,  17.9,  43.2,
        65.7,  58.7,   5.3,  69.2,  21.4,   9.3,   5. ,  18.3,   5.8,
         8.4,   8.5,  23.7,  47.4,   8.1,   8.5,  24.3,  13.1,  39.6,
        56.5,  54.7,  22.9,  23.5,  46. ,  30. ,  12.9,  38.9,  30. ,
        38.6, 100.9,  25.6,  26.4,  37.7,  58.5,  38.7,  49.6,  74.2,
        34.6,  23.2,  32. ,   2.2,   3.2,  38.7,  45.7,  52.9,  22.9,
        21.6,  51.4,  50.6,  65.9,  36.9,  35.2,  50.5,  44.3,   2.1,
        28.9,   0.9,  10.7,  21.4,  89.4,  14.8,   6. ,  49.9,  22. ,
        40.8,  41.8,  37.7,  59. ,  57.6,  59.7,  17. ,  63.2,  29.7,
        26.2,  10.2,   1.7,  33. ,  12.6,  31.6,   8.7,  15.6,  14.2,
         0.3,  75.6,  84.8,  43.3,  14.2,  12.4,  48.7,  27.4,  51.2,
         1.8,  12.8,

In [19]:
lin_reg = LinearRegression()
lin_reg.fit(X_train.reshape(-1,1), y_train)

LinearRegression()

In [20]:
print(f"y  = {lin_reg.intercept_} + {lin_reg.coef_[0]} x")


y  = 12.005089411415938 + 0.06864893649775611 x


In [21]:
y_pred= lin_reg.predict(X_test.reshape(-1,1))
y_pred

array([12.60233516, 12.82201176, 17.15375965, 12.62292984, 13.41239261,
       12.64352452, 12.95244474, 16.50845965, 13.5359607 , 13.27509474,
       15.10115645, 12.25222558, 19.83106817, 13.21331069, 13.34374367,
       12.80141707, 16.93408305, 16.05537666, 13.26136495, 14.53137027,
       15.83570007, 12.41698303, 12.51309154, 13.76250219, 15.62288836,
       12.51309154, 13.3162841 , 12.44444261, 14.04396283, 12.25222558,
       14.23617985, 15.10115645, 15.46499581, 13.35060857, 13.14466176,
       13.78309687, 14.95699368, 14.1812607 , 13.87920538, 12.44444261])

In [22]:
r2_score(y_test, y_pred)

-0.08810135767789262

In [34]:
x = data_df.drop('sales', axis = 1).to_numpy()
y = data_df['sales'].to_numpy()


In [35]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 989)

In [36]:
X_train

array([[191.1,  28.7,  18.2],
       [ 11.7,  36.9,  45.2],
       [ 50. ,  11.6,  18.4],
       [ 25.6,  39. ,   9.3],
       [ 88.3,  25.5,  73.4],
       [187.8,  21.1,   9.5],
       [ 17.2,  45.9,  69.3],
       [255.4,  26.9,   5.5],
       [  0.7,  39.6,   8.7],
       [125.7,  36.9,  79.2],
       [104.6,   5.7,  34.4],
       [222.4,   4.3,  49.8],
       [107.4,  14. ,  10.9],
       [172.5,  18.1,  30.7],
       [116. ,   7.7,  23.1],
       [135.2,  41.7,  45.9],
       [188.4,  18.1,  25.6],
       [ 44.7,  25.8,  20.6],
       [131.7,  18.4,  34.6],
       [213.4,  24.6,  13.1],
       [  5.4,  29.9,   9.4],
       [175.1,  22.5,  31.5],
       [ 59.6,  12. ,  43.1],
       [250.9,  36.5,  72.3],
       [139.5,   2.1,  26.6],
       [ 76.4,  26.7,  22.3],
       [220.5,  33.2,  37.9],
       [283.6,  42. ,  66.2],
       [ 68.4,  44.5,  35.6],
       [ 43.1,  26.7,  35.1],
       [214.7,  24. ,   4. ],
       [ 27.5,   1.6,  20.7],
       [280.7,  13.9,  37. ],
       [ 2

In [43]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [45]:
lin_reg.intercept_, lin_reg.coef_

(np.float64(2.78573236536438), array([0.04591099, 0.18628694, 0.00408379]))

In [46]:
print(f"y  = {lin_reg.intercept_} + {lin_reg.coef_[0]} x1 + {lin_reg.coef_[1]} x2 + {lin_reg.coef_[2]} x3")

y  = 2.78573236536438 + 0.04591098995168594 x1 + 0.18628694185692812 x2 + 0.004083788345078271 x3


In [47]:
y_pred= lin_reg.predict(X_test)
y_pred

array([15.07926979, 12.08631082, 12.60087356,  9.61774354,  9.66845439,
       17.99262196,  5.28515015, 11.93842037,  6.74806512, 21.60623703,
       19.30175936, 18.28243869, 13.18215143, 12.32333639, 15.58736979,
       12.00282936, 24.29328758, 18.00151549,  9.8563885 ,  8.18701822,
       23.30992322, 16.31492542, 17.17775872, 11.94499042, 12.96890632,
        7.47043586, 14.07867945, 12.67058239,  6.10395199,  9.19825204,
       10.15717795, 12.33402709,  7.89710855, 20.67906863, 12.68330937,
        9.09312672, 15.67716193, 10.62011842, 16.77116728, 17.83900464])

In [48]:
r2_score(y_test, y_pred)

0.8803284407869357